import { UserRole, RoleConfig, UserProfile } from '../types/auth';

export const ROLE_CONFIGS: Record<UserRole, RoleConfig> = {
  patient: {
    role: 'patient',
    title: 'Patient Portal',
    subtitle: 'Sign in to access your consultations, health records & medical appointments',
    iconName: 'person-outline',
    identifierLabel: 'Email or Mobile Number',
    identifierPlaceholder: 'name@domain.com or 10-digit number',
    identifierRightActionText: 'UHID / Patient ID',
    defaultEmailOrId: 'patient@gmail.com',
    demoPassword: '••••••••••••',
    portalName: 'Patient Health Dashboard',
    primaryColor: '#0080FF',
    badgeText: 'Verified Patient',
  },
  doctor: {
    role: 'doctor',
    title: 'Doctor OPD Portal',
    subtitle: 'Sign in to manage your OPD queues, clinic schedules & consultations',
    iconName: 'medkit-outline',
    identifierLabel: 'Doctor Email or Mobile Number',
    identifierPlaceholder: 'doctor@domain.com or NMC / Reg No',
    identifierRightActionText: 'NMC / Reg No',
    defaultEmailOrId: 'docdummy@gmail.com',
    demoPassword: '••••••••••••',
    portalName: 'Doctor OPD & Clinics',
    primaryColor: '#0284C7',
    badgeText: 'NMC Verified Doctor',
  },
  clinic: {
    role: 'clinic',
    title: 'Clinic & Reception Portal',
    subtitle: 'Sign in to manage OPD queues, patient tokens & live clinic operations',
    iconName: 'business-outline',
    identifierLabel: 'Clinic Code or Reception Email',
    identifierPlaceholder: 'clinic@domain.com or Clinic License ID',
    identifierRightActionText: 'Clinic Reg ID',
    defaultEmailOrId: 'themishraunit@gmail.com',
    demoPassword: '••••••••••••',
    portalName: 'Clinic Operations & Queue Hub',
    primaryColor: '#2563EB',
    badgeText: "Mishra's Medical Reception",
  },
  lab: {
    role: 'lab',
    title: 'Diagnostic & Lab Portal',
    subtitle: 'Sign in to manage diagnostic orders, sample collections & test reports',
    iconName: 'flask-outline',
    identifierLabel: 'Lab Code or Admin Email',
    identifierPlaceholder: 'lab@domain.com or Lab License ID',
    identifierRightActionText: 'Diagnostic Reg ID',
    defaultEmailOrId: 'diag3@gmail.com',
    demoPassword: '••••••••••••',
    portalName: 'Diagnostic Sample & Report Hub',
    primaryColor: '#0D9488',
    badgeText: 'NABL Accredited Lab',
  },
};

export const DEMO_USERS: Record<UserRole, UserProfile> = {
  patient: {
    id: '679342b9-f878-4431-9f19-b00001306f81',
    name: 'Sanjay Sharma',
    role: 'patient',
    identifier: 'UPC-PAT-679342',
    email: 'patient@gmail.com',
    phone: '+91 65784 51245',
    avatarUrl:
      'https://wusyykhngnxglvftrmrb.supabase.co/storage/v1/object/public/avatars/679342b9-f878-4431-9f19-b00001306f81/avatar.jpg?t=1778101370787',
    specialtyOrTagline: 'UHID: UPC-PAT-679342 • Blood Group O+',
    bloodGroup: 'O+ Positive',
    dateOfBirth: '14 / 08 / 1994',
    gender: 'male',
    address: 'Green Valley, New Delhi',
    isVerified: true,
  },
  doctor: {
    id: 'bbb0cb11-e95d-4530-a973-0741b6de5bd6',
    name: 'Dr. Rudranil',
    role: 'doctor',
    identifier: 'DOC-REG-BBB0CB',
    email: 'docdummy@gmail.com',
    phone: '+91 89632 14789',
    avatarUrl:
      'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80',
    specialtyOrTagline: 'General Physician • 10+ Yrs Exp',
    isVerified: true,
  },
  clinic: {
    id: 'f3ac4f14-fed0-4574-b262-4ca17ac3bf8c',
    name: "Mishra's Medical",
    role: 'clinic',
    identifier: 'CLI-REG-F3AC4F',
    email: 'themishraunit@gmail.com',
    phone: '+91 74074 07407',
    avatarUrl:
      'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=200&q=80',
    specialtyOrTagline: "Mishra's Medical • Asansol, West Bengal",
    address: 'Asansol, West Bengal - 713304',
    isVerified: true,
  },
  lab: {
    id: 'a572938e-c560-4c52-b289-ae7180b61e04',
    name: 'Diag3 Diagnostic Centre',
    role: 'lab',
    identifier: 'LAB-NABL-A57293',
    email: 'diag3@gmail.com',
    phone: '+91 99992 22333',
    avatarUrl:
      'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=200&q=80',
    specialtyOrTagline: 'NABL Accredited • Diagnostic & Pathology Center',
    isVerified: true,
  },
};
